"""Изменено поле dynamic на True

Revision ID: 8edce5e18f9b
Revises: f53da71ee099
Create Date: 2025-11-25 14:25:22.490590

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8edce5e18f9b'
down_revision: Union[str, Sequence[str], None] = 'f53da71ee099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cryptos', 'dynamic',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cryptos', 'dynamic',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
